import type { Finding } from "@/lib/security-scan";
import { SITE } from "@/lib/data";

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

type StatusResult = {
  statusCode: number;
  statusText: string;
  responseTimeMs: number;
  server: string | null;
  contentType: string | null;
  tls: { valid: boolean; issuer: string | null; validTo: string | null; daysRemaining: number | null } | null;
  securityHeaders: { name: string; present: boolean }[];
};

export function buildStatusReport(url: string, result: StatusResult): string {
  const lines = [
    `STACK-CORE Status Check — ${SITE.name}`,
    `Target: ${url}`,
    `Generated ${new Date().toISOString()}`,
    "",
    `Status: ${result.statusCode} ${result.statusText}`,
    `Response time: ${result.responseTimeMs}ms`,
    `Server: ${result.server ?? "Not disclosed"}`,
    `Content-Type: ${result.contentType ?? "Unknown"}`,
    "",
    "TLS Certificate:",
    result.tls
      ? [
          `  Valid: ${result.tls.valid}`,
          result.tls.issuer ? `  Issuer: ${result.tls.issuer}` : null,
          result.tls.daysRemaining !== null ? `  Expires in: ${result.tls.daysRemaining} days` : null,
        ]
          .filter(Boolean)
          .join("\n")
      : "  N/A (http or unavailable)",
    "",
    "Security Headers:",
    result.securityHeaders.map((h) => `  [${h.present ? "PRESENT" : "MISSING"}] ${h.name}`).join("\n"),
    "",
    `Generated by ${SITE.name} (${SITE.email})`,
  ];
  return lines.join("\n");
}

export function buildContrastReport(
  foreground: string,
  background: string,
  result: { ratio: number; normalAA: boolean; normalAAA: boolean; largeAA: boolean; largeAAA: boolean }
): string {
  const lines = [
    `PIXEL-UX Contrast Report — ${SITE.name}`,
    `Generated ${new Date().toISOString()}`,
    "",
    `Foreground: ${foreground}`,
    `Background: ${background}`,
    `Contrast ratio: ${result.ratio.toFixed(2)}:1`,
    "",
    `AA — Normal text: ${result.normalAA ? "PASS" : "FAIL"}`,
    `AAA — Normal text: ${result.normalAAA ? "PASS" : "FAIL"}`,
    `AA — Large text: ${result.largeAA ? "PASS" : "FAIL"}`,
    `AAA — Large text: ${result.largeAAA ? "PASS" : "FAIL"}`,
    "",
    `Generated by ${SITE.name} (${SITE.email})`,
  ];
  return lines.join("\n");
}

export function buildFindingsReport(title: string, findings: Finding[]): string {
  const lines = [
    `${title} — ${SITE.name}`,
    `Generated ${new Date().toISOString()}`,
    "",
    findings.length === 0
      ? "No issues found by these heuristics."
      : findings
          .map((f) => `[${f.severity.toUpperCase()}] line ${f.line}: ${f.message}`)
          .join("\n"),
    "",
    `${findings.length} finding(s) — generated by ${SITE.name} (${SITE.email})`,
  ];
  return lines.join("\n");
}
